export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";

export const DASHBOARD_CREATE_PRODUCT = "DASHBOARD_CREATE_PRODUCT";
export const DASHBOARD_UPDATE_PRODUCT = "DASHBOARD_UPDATE_PRODUCT";
export const DASHBOARD_DELETE_PRODUCT = "DASHBOARD_DELETE_PRODUCT";
