export const DASHBOARD_LOAD_PRODUCTS = "DASHBOARD_LOAD_PRODUCTS";
export const DASHBOARD_CREATE_PRODUCT = "DASHBOARD_CREATE_PRODUCT";
export const DASHBOARD_UPDATE_PRODUCT = "DASHBOARD_UPDATE_PRODUCT";
export const DASHBOARD_DELETE_PRODUCT = "DASHBOARD_DELETE_PRODUCT";
